### ISSUE TITLE
example_bmp2png.cpp process 32bit bmp incorrectly

### ISSUE THREAD

**Issue by roytam1** [lvandeve/lodepng#112]
it should be in this:

````
    } else {
      image[newpos + 0] = bmp[bmpos + 2]; //R
      image[newpos + 1] = bmp[bmpos + 1]; //G
      image[newpos + 2] = bmp[bmpos + 0]; //B
      image[newpos + 3] = bmp[bmpos + 3]; //A
    }
````

**Comment by lvandeve** [comment]
Thank you for reporting this. Do you happen to have an example 32bit bmp image to test this on?

**Comment by roytam1** [comment]
sure.
[Desktop Background.zip](https://github.com/lvandeve/lodepng/files/3796022/Desktop.Background.zip)

**Comment by lvandeve** [comment]
Thanks!

Fixed in commit https://github.com/lvandeve/lodepng/commit/957506a7c21db4000685dae340034253834e37da
