### ISSUE TITLE
Decoding error 55: jumped past tree while generating huffman tree

### ISSUE THREAD

**Issue by JayXon** [lvandeve/lodepng#114]
After zopfli updated to latest lodepng (https://github.com/google/zopfli/commit/5d9b71b3c636e9e14a8f7a3f983ff93a1a3793ac), I've noticed that some png failed to decode with error 55, but the image is displayed just fine by other software, is lodepng being too strict or the image is actually broken?

Test file:
![05-c3-c2](https://user-images.githubusercontent.com/1552641/68176235-d3e89f80-ff38-11e9-90e8-fbda51f3ef01.png)

**Comment by lvandeve** [comment]
Thanks for reporting! Found what it is and fixed in commit https://github.com/lvandeve/lodepng/commit/3606db5a71359a4165308e7cd5afe67bd42f7edf, it was broken support for huffman trees with 0 or 1 actual symbols in it after rewriting the huffman decoding to be faster.

**Comment by JayXon** [comment]
Thanks for the quick fix! Could you update lodepng in zopfli again?

**Comment by lvandeve** [comment]
Yep, done
