### ISSUE TITLE
The entropy strategy implemented with integer gives worse compression than float version

### ISSUE THREAD

**Issue by JayXon** [lvandeve/lodepng#116]
One of the regressions after updating lodepng in zopfli is that it choses entrop strategy less often than before.
![20-c6-shouldbe-c4-rgbdata](https://user-images.githubusercontent.com/1552641/68380269-5a051180-0104-11ea-95d7-3af8477443b3.png)
For example this file, `zopflipng --lossy_transparent` now chooses zero strategy and optimize it to 5811 bytes while previously it chooses entropy and optimize it to 5642 bytes.
Even if I force entropy strategy with `--filters=e`, 5719 bytes is still not as good as before.

I nailed it down to this commit https://github.com/lvandeve/lodepng/commit/3d639635bb1b00ef21d11ce478373991c3eca1d5 and verified that after reverting it can now optimize to 5642 bytes like before.

What's the rationale behind removing usage of float? Is it for speed? I did not notice any speed difference in my testing.

**Comment by lvandeve** [comment]
I could consider implementing this strategy with floating point in zopfli itself, it definitely belongs more there than in the PNG library

**Comment by zvezdochiot** [comment]
@JayXon say:
>I nailed it down to this commit 3d63963

https://github.com/lvandeve/lodepng/blob/c84cff3a5411bd15c70a18c900852b20f32077cc/lodepng.cpp#L5468

Maibe:
```c
 sum[type] += count[x] == 0 ? 0 : (ilog2(linebytes + 1) - ilog2(count[x])) * count[x] / (linebytes + 1);
```

**Comment by zvezdochiot** [comment]
https://github.com/lvandeve/lodepng/blob/c84cff3a5411bd15c70a18c900852b20f32077cc/lodepng.cpp#L5461-L5475

Maybe?:
```c
      bestSum = 0;
      bestType = 0;
      for(type = 0; type < 5; ++type) {
        filterScanline(attempt[type], &in[y * linebytes], prevline, linebytes, bytewidth, type);
        for(x = 0; x < 256; ++x) count[x] = 0;
        for(x = 0; x < linebytes; ++x) ++count[attempt[type][x]];
        ++count[type]; /*the filter type itself is part of the scanline*/
        sum[type] = 0;
        for(x = 0; x < 256; ++x) {
          sum[type] += (count[x] == 0) ? 0 : ilog2(count[x]) * count[x];
        }
        if(sum[type] > bestSum) {
          bestType = type;
          bestSum = sum[type];
        }
      }
```

**Comment by zvezdochiot** [comment]
https://github.com/lvandeve/lodepng/blob/c84cff3a5411bd15c70a18c900852b20f32077cc/lodepng.cpp#L5461-L5475

Maybe?:
```c
      bestSum = 0;
      bestType = 0;
      for(type = 0; type < 5; ++type) {
        filterScanline(attempt[type], &in[y * linebytes], prevline, linebytes, bytewidth, type);
        for(x = 0; x < 256; ++x) count[x] = 0;
        for(x = 0; x < linebytes; ++x) ++count[attempt[type][x]];
        ++count[type]; /*the filter type itself is part of the scanline*/ 
        sumt = 0;
        for(x = 0; x < 256; ++x) {
          sumt += (count[x] == 0) ? 0 : ilog2(count[x] * count[x]) * count[x] / 2;
        }
        if(sumt > bestSum) {
          bestType = type;
          bestSum = sumt;
        }
      }
```

**Comment by lvandeve** [comment]
Another formula to try for an improved integer approximation:

ilog2(x) * x + x - (1 << ilog2(x))

**Comment by zvezdochiot** [comment]
@lvandeve say:
>ilog2(x) * x + x - (1 << ilog2(x))

Good. See up.

**Comment by zvezdochiot** [comment]
But should not there be a harmonic mean, and not an arithmetic mean?

**Comment by lvandeve** [comment]
Yes indeed, f4 is best, I forgot a factor of 2 above. 

It works well for zopfli on the attached image file with the --lossy_transparent setting and without giving --filters=e

I think this solves the issue nicely without needing to add it with float in zopfli, leaving open for now for further feedback

**Comment by zvezdochiot** [comment]
@lvandeve say:
>leaving open for now for further feedback

Not only. It is worthwhile to conduct an additional set of tests on sub-issues. The topic is not exhausted.

**Comment by JayXon** [comment]
The new algorithm is actually better than the previous float version! Thanks!
