### ISSUE TITLE
memory allocation failed

### ISSUE THREAD

**Issue by simonchen007** [lvandeve/lodepng#128]
I'm using esp32 + lvgl + lv_lib_lodepng,
but when I use a png more 20K , it would shows "memory allocation failed", is that possbile to  change  the memory allocation bigger ?

**Comment by zvezdochiot** [comment]
:question: lv_lib_lodepng - what is it?

**Comment by simonchen007** [comment]
sorry, I type wrong, lv_lib_lodepng  is  https://github.com/lvandeve/lodepng

**Comment by lvandeve** [comment]
I think the issue is being handled here: https://github.com/lvgl/lv_lib_lodepng/issues/2

so I'll close this one, feel free to reopen if you believe it's caused by lodepng itself
