### ISSUE TITLE
Request: Standalone encoder

### ISSUE THREAD

**Issue by crazybob** [lvandeve/lodepng#150]
We don't need decoding in our embedded system. Thank you for the great code!

**Comment by lvandeve** [comment]
You can pass a macro LODEPNG_NO_COMPILE_DECODER to the compiler to disable all the decoder code with #ifdefs. There are more features that you can disable, take a look near the top of lodepng.h. Does that work?

**Comment by crazybob** [comment]
Perfect, thank you!
