### ISSUE TITLE
Add LODEPNG_NO_COMPILE_CRC flag

### ISSUE THREAD

**Issue by OldFisher** [lvandeve/lodepng#16]
I think this flag should be added. Just as it is with zlib, someone could use LodePNG and CRC32 routines in same project, so no point in duplicating the code and the tables.

**Comment by lvandeve** [comment]
Do you mean it would then just declare the crc function in lodepng.c, and you'd define it in another source file?

**Comment by OldFisher** [comment]
Yes, that's exactly what I meant.

**Comment by lvandeve** [comment]
Done, thank you for the good idea

**Comment by OldFisher** [comment]
Great, thank you for quick response and generally for this neat and useful library.
