### ISSUE TITLE
W64

### ISSUE THREAD

**Issue by fastrgv** [lvandeve/lodepng#163]
Just a question: Is there any reason you know of that would prevent lodepng from working under 64-bit Windows?
Thx.

**Comment by lvandeve** [comment]
No, it should work. Which compiler are you using, or which error do you get?

Thanks

**Comment by fastrgv** [comment]
My mistake. Lodepng is fine. I got a couple of your examples working.
I am using the AdaCore g++ compiler that ships with Ada.
The examples work nicely with both the 32-bit compiler (2017) and the 64-bit (2020).
By the way, with this setup, you do not need MingW.

I am working on puzzle games with my own OpenAL interface for sound, and that use OpenGL.
They work under W32 but not W64, but not because of lodepng.
Thank You
Rod <fastrgv@gmail.com>

ps See https://sourceforge.net/projects/rufasslider/
which uses an older version of lodepng, which I am updating,
as well as trying to get it working for W64.
