### ISSUE TITLE
sdl2

### ISSUE THREAD

**Issue by fastrgv** [lvandeve/lodepng#164]
I think you need an example that uses a more modern SDL2. Here is mine
[lod.tar.gz](https://github.com/lvandeve/lodepng/files/8549786/lod.tar.gz)
:

**Comment by fastrgv** [comment]
Sorry, I forgot to edit the comments at the top, appropriately. I'll leave that to you. I expect you'll want to edit anyway.

**Comment by fastrgv** [comment]
Here is a more complete version that has build scripts for OSX, W32, W64, & linux
[lod.tar.gz](https://github.com/lvandeve/lodepng/files/8597055/lod.tar.gz)
:

**Comment by fastrgv** [comment]
Finally, here is an explanation file:

[README.md](https://github.com/lvandeve/lodepng/files/8597763/README.md)

**Comment by lvandeve** [comment]
Good point, converted the examples to SDL2 now, using the migration guide (https://wiki.libsdl.org/MigrationGuide)

**Comment by fastrgv** [comment]
It worked perfectly for me. Nice!

**Comment by fastrgv** [comment]
In case I have not mentioned it before...

https://sourceforge.net/projects/rufasslider/files/27apr2022/

is my "modern-OpenGL" set of puzzles that uses lodepng and runs on Windows, Linux & OSX.
(all my other games use the Ada programming language).
Rod
