### ISSUE TITLE
 chunk type is restricted to the decimal values 65 to 90 and 97 to 122

### ISSUE THREAD

**Issue by boofish** [lvandeve/lodepng#181]
Hi, according to the [specification](https://www.w3.org/TR/2003/REC-PNG-20031110/#5Chunk-layout), chunk type is restricted to the decimal values 65 to 90 and 97 to 122. 

Maybe this could be fixed at the function `decodeGeneric` by replacing 
```
else /*it's not an implemented chunk type, so ignore it: skip over the data*/ {
      /*error: unknown critical chunk (5th bit of first byte of chunk type is 0)*/
      if(!state->decoder.ignore_critical && !lodepng_chunk_ancillary(chunk)) {
        CERROR_BREAK(state->error, 69);
      }
```
with
```
else /*it's not an implemented chunk type, so ignore it: skip over the data*/ {
      /*error: unknown critical chunk (5th bit of first byte of chunk type is 0)*/
      unsigned i;
      for(i = 0; i != 4; ++i) 
        if (!((chunk[i+4]>='a' && chunk[i+4]<='z') || (chunk[i+4]>='A' && chunk[i+4]<='Z'))) {
            CERROR_BREAK(state->error, 116); // invalid chunk type
        }
      if(!state->decoder.ignore_critical && !lodepng_chunk_ancillary(chunk)) {
        CERROR_BREAK(state->error, 69);
      }
```
This rule is meaningful and it can allow safe, flexible extension of the PNG format according to the specification.

**Comment by lvandeve** [comment]
Done in https://github.com/lvandeve/lodepng/commit/5a2e75116929fde59ea4e82585176cd4ceb29a22, in addition also checked for the 'reserved' bit that's not allowed and fixed another error found through this
