### ISSUE TITLE
Fix lodev.org SSL certificate, change to https

### ISSUE THREAD

**Issue by BenWiederhake** [lvandeve/lodepng#19]
I'm using Firefox, which refuses to load the HTTPS version of your homepage:

```
lodev.org uses an invalid security certificate.
The certificate is not trusted because the issuer certificate is unknown.
The certificate is only valid for server54.hostpoint.ch
(Error code: sec_error_unknown_issuer)
```

After this is fixed, I suggest changing `README.md:6` to the https version.

Ideally, `grep -rn http:` would yield no match within the sourcecode. However, the existing references (w3.org and gzip.org) do not support HTTPS yet, so there's nothing to change in lodepng (not yet).

**Comment by lvandeve** [comment]
There isn't an HTTPS version of lodev.org. Was there a link somewhere that brought you to https://lodev.org?

Thank you.

**Comment by BenWiederhake** [comment]
I wanted to see whether the in-line links to lodev.org can be switched to https, so I copied the URL and changes the protocol to https to see what happens.

I don't think that it's good to leave the port open if it doesn't really support https, which is why I wanted to report it.
Of course, there's other ways to resolve this: (1) Closing the port, (2) using actual encryption (3) plaintext response that redirects to the http-only version, and maybe others.

**Comment by lvandeve** [comment]
It seems redirecting from https to http or any other response without certificate is impossible by definition. The current behaviour seems to be related to the web host and not configurable by me afaik. I'm currently not planning to support https on this site.
