### ISSUE TITLE
Please add support for HDR imagery (Third Edition of PNG specification)

### ISSUE THREAD

**Issue by MarkCallow** [lvandeve/lodepng#192]
including the cICP chunk.

**Comment by AntTheAlchemist** [comment]
I would also be very interested in this. SDL3 recently moved over to using floats to represent RGBA and has added 32-bit pixel formats.

**Comment by lvandeve** [comment]
Yes it'd be useful to support this and other third edition spec chunks. Now just added support for the exif chunk, and some of the HDR chunks will follow later

**Comment by lvandeve** [comment]
Added support for the cICP chunk now in https://github.com/lvandeve/lodepng/commit/0fbd2b27b79a4e8bf2672ada1f404fc9add31f8a

lodepng itself will not interpret the values in any way, it just passes them on to the user (either outputs them in the png info if they were present in the image, or writes them if the user sets them in the png info)

**Comment by lvandeve** [comment]
And finally added support for the mDCv and cLLi chunks: https://github.com/lvandeve/lodepng/commit/44cdab80e1c55d6b5decae3596a17c3c4c3c3c7c

Since the spec is draft, if the format of the chunks would still change it'll need to be changed here as well
