### ISSUE TITLE
No support for images larger than 65535x65535?

### ISSUE THREAD

**Issue by rafa-br34** [lvandeve/lodepng#193]
```
Thread 2 "[...]" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffdf7a4c640 (LWP 85229)]
0x0000555555577c24 in filterScanline (out=out@entry=0x7ffdf0011842 "", scanline=scanline@entry=0x7ffdf7a5d010 "", prevline=0x7ffdf7a4d010 "", length=length@entry=65536, bytewidth=bytewidth@entry=1, filterType=filterType@entry=0 '\000') at /home/rafa/[...]/LIBRARIES/lodepng/lodepng.cpp:5835
5835          for(i = 0; i != length; ++i) out[i] = scanline[i];
(gdb)
```
Anything larger than 65535x65535 seems to cause a segfault (likely integer overflow as 65535 * 65535 = 4294836225).
The binary was compiled for 64-bit and in RelWithDebInfo config.
```
ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=09ce097fba73973fd8fcda17d069433e182e2ffe, for GNU/Linux 3.2.0, with debug_info, not stripped
```

**Comment by lvandeve** [comment]
Thanks for reporting, indeed several things were broken for buffers larger than 4GB, some fixes were applied here: https://github.com/lvandeve/lodepng/commit/0cc108ebd1a9cd5dabd8dde86622cc9b012f7340

Does it work now for you? I'll try to fix any further problems that arise

**Comment by rafa-br34** [comment]
I've got a few warnings on MSVC due to some casts. It compiles fine and works fine with 70000x70000, but due to memory constraints, I wasn't able to try higher resolutions on my Windows PC.
I tested with 128000x128000 and 512000x512000 on a Linux workstation, I wasn't patient enough to allow the 512000x512000 image to finish encoding, but 128000x128000 worked perfectly.

Here's what MSVC outputs if you're interested in fixing the warnings, up to you tho :)
```
[build] [...]\lodepng.cpp(1753,71): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
[build] [...]\lodepng.cpp(6201,76): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
[build] [...]\lodepng.cpp(6202,72): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
[build] [...]\lodepng.cpp(6207,66): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
[build] [...]\lodepng.cpp(6215,95): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
[build] [...]\lodepng.cpp(6227,43): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
```
I'll close the issue since I believe this has been fixed, thanks for the quick response and fix.
