### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by paulsapps** [lvandeve/lodepng#25]
Need to check its compatible with MIT license.

**Comment by lvandeve** [comment]
Hi,

It's the zlib license (https://en.wikipedia.org/wiki/Zlib_License). You can find it at the top of the source files.

I'm not a laywer so can't comment on compatibilities with other licenses, but you can probably look it up :)

**Comment by paulsapps** [comment]
Thanks, maybe its worth adding a LICENSE file for clarity.
