### ISSUE TITLE
'lodepng' or 'loadpng'?

### ISSUE THREAD

**Issue by CharlesDong** [lvandeve/lodepng#48]
I have a question about the name: Why is this called 'lodepng'? Shouldn't it be 'loadpng'?

**Comment by jslee02** [comment]
You should check the name of the author! :smile:

**Comment by CharlesDong** [comment]
Thanks for @jslee02. Actually, I've understand a few minutes ago. That's his name (and it's similar to 'load'). :)

**Comment by lvandeve** [comment]
Yes, that's it indeed :)
