### ISSUE TITLE
Compilation without libc?

### ISSUE THREAD

**Issue by DeXP** [lvandeve/lodepng#7]
lodepng can work without libc. Maybe, wrap "strlen", "qsort" and "memset" functions like "lodepng_malloc"?

The current implementation is getting enough dirty:
https://github.com/DeXP/dxPmdxConverter/blob/master/bmpconvert.c

**Comment by lvandeve** [comment]
Hi,

I can look into it. A question about this: what is a scenario where this is needed? Which device is this for?

Thanks :)

**Comment by DeXP** [comment]
Hi!
I don't know, where is it really needed. I'm making windows application without dependencies, with minimal EXE-size and maximum functionality. But it is hacking and for fun.

**Comment by lvandeve** [comment]
this is done now, only one C header (string.h) used for size_t only, and the file loading is optional.
