### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [lvandeve/lodepng#90]
Greetings lodepng developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run all the fuzzers you write.

- Alert you when it finds issues.

- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

<ADD THIS IF WE HAVE AUTO-GENERATED FUZZ TARGETS>  To help you getting started, we attached our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://github.com/google/oss-fuzz/blob/master/docs/faq.md ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

```c++
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>
#include "lodepng.h"

namespace {

LodePNGColorType SelectColorType(const uint8_t** data, size_t* size) {
  uint8_t color_type_selector = 0;
  if (*size >= 1) {
    color_type_selector = *data[0];
    *data += 1;
    *size -= 1;
  }
  const std::vector<LodePNGColorType> colorTypes{LCT_GREY, LCT_RGB, LCT_PALETTE,
                                                 LCT_GREY_ALPHA, LCT_RGBA};
  return colorTypes.at(color_type_selector % colorTypes.size());
}

}  // namespace

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
  if (size == 0) {
    return EXIT_SUCCESS;
  }
  const LodePNGColorType wantColorType = SelectColorType(&data, &size);

  const unsigned char* buffer = reinterpret_cast<const unsigned char*>(data);

  LodePNGState lp{};
  lodepng_state_init(&lp);

  unsigned int lp_w{};
  unsigned int lp_h{};
  const unsigned inspect_err = lodepng_inspect(&lp_w, &lp_h, &lp, buffer, size);
  if (inspect_err != 0) {
    lodepng_state_cleanup(&lp);
    return EXIT_SUCCESS;
  }

  std::vector<unsigned char> outBuffer{};
  unsigned int w{};
  unsigned int h{};
  lodepng::decode(outBuffer, w, h, buffer, wantColorType);

  lodepng_state_cleanup(&lp);
  return EXIT_SUCCESS;
}
```

**Comment by lvandeve** [comment]
Thank you for accepting!

This is done, closing issue
